#!/usr/bin/env sh

ARG1="$1"
CP="target/classes:lib/*"
MAIN_PATH="src/main/java/com/taylorscript/main/"

if [[ $ARG1 == "-cmp" ]]; then
    mvn compile
    exit 0
fi


if [[ $ARG1 == "-ast" ]]; then
    java -cp "$CP" com.taylorscript.tool.GenerateAst "$MAIN_PATH"
    exit 0
elif [[ ! (-z $ARG1) ]]; then
    java -cp "$CP" com.taylorscript.main.TaylorScript "$ARG1"
    exit 0
else
    java -cp "$CP" com.taylorscript.main.TaylorScript   
fi
