#!/usr/bin/env sh

ARG1="$1"
CP="target/classes"

if [[ $ARG1 == "-cmp" ]]; then
    mvn compile
    exit 0
fi


if [[ ! (-z $ARG1) ]]; then
    java -cp "$CP" com.taylorscript.main.TaylorScript "$ARG1"
    exit 0
else
    java -cp "$CP" com.taylorscript.main.TaylorScript   
fi
